server:
  port: 9080

spring:
  application:
    name: chatbot_spring
  datasource:
    url: jdbc:mysql://localhost:3305/chatbot_db?serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieu01bdvn@gmail.com
    # This is password in feature "app password" of gmail
    password: dwle xmjw pjgg jzju
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: chatbot_spring
    server: http://localhost:${server.port}
    title: chatbot_spring service
    version: 1.0.0

# different configs
jwt:
  secretKey: Xv1MsBY3sOf96Zefj4wJoYbqk9a4cs2Jz8ln+mOoDUEGp78E2Wy3TDGx/HfzZ9VB